name: flutter_camera
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.5+9
  flutter_riverpod: ^2.4.9
  photo_view: ^0.14.0
  native_camera_sound: ^0.0.3
  shared_preferences: ^2.2.2
  path_provider: ^2.1.2
  permission_handler: ^11.2.0
  audioplayers: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/sound/shutter.mp3
